name: Install MinIO (Docker)

on:
  workflow_dispatch:

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_TEST_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}

jobs:
  install-minio:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and install MinIO
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{ secrets.STAGE_SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.STAGE_SERVER_PRIVATE_SSH_KEY }}
          script: |
            # Run MinIO
            docker run -d \
              -p ${MINIO_PORT}:9000 \
              -p ${MINIO_CONSOLE_PORT}:9090 \
              --name ${MINIO_CONTAINER_NAME} \
              -v ${MINIO_DATA_DIR}:/data \
              -e "MINIO_ROOT_USER=${{ env.MINIO_ROOT_USER }}" \
              -e "MINIO_ROOT_PASSWORD=${{ env.MINIO_ROOT_PASSWORD }}" \
              -e "MINIO_ACCESS_KEY=${{ env.MINIO_ACCESS_KEY }}" \
              -e "MINIO_SECRET_KEY=${{ env.MINIO_SECRET_KEY }}" \
              ${MINIO_IMAGE} server /data --console-address ":9090"