# Create a new SSH key
# ssh-keygen -t rsa

# Connect to server
# mkdir -p ~/.ssh
# echo your_public_key >> ~/.ssh/authorized_keys

# ENVIRONMENT VARIABLES
# STAGE_SERVER_HOST
# STAGE_SERVER_USERNAME
# STAGE_SERVER_PRIVATE_SSH_KEY

name: 1. Setup Server

on:
  workflow_dispatch:

jobs:
  install-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and install softwares
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{ secrets.STAGE_SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.STAGE_SERVER_PRIVATE_SSH_KEY }}
          script: |
            # Check if Docker Compose is already installed
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose is already installed."
            fi

            # Check if Nginx Proxy Manager is already installed
            if [ ! -d "~/nginx-proxy-manager" ]; then
              echo "Nginx Proxy Manager not found, installing..."
              mkdir ~/nginx-proxy-manager && cd ~/nginx-proxy-manager

              echo "Nginx Proxy Manager is now running."
            else
              echo "Nginx Proxy Manager is already installed."
            fi